site_name: Building Beautiful Docs Workshop
site_description: A small sample project demonstrating one way to generate a docs site for your PowerShell modules.
site_dir: Output/site
repo_url: https://github.com/joshooaj/PSHSummit24Workshop
remote_branch: gh-pages

theme:
  name: material
  logo: assets/images/joshooaj.png
  favicon: assets/images/joshooaj.png
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: material/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.copy           # Add a "copy" button to all code blocks
    - content.code.annotate       # Enable the use of interactive annotations (+) in code blocks
    - content.tabs.link           # Add anchors
    - toc.integrate               # Integrate table-of-contents into the left-side navigation. ToC is normally rendered on the right
    - toc.follow                  # Scrolls the sidebar so that the active anchor is always visible
    - navigation.instant          # Page loads like a single page application (SPA) so clicks are "instant"
    - navigation.instant.progress # On initial page load, a progress ring is shown to indicate when the page load has fully completed
    - navigation.tabs             # Moves top-level navigation items to the header
    - navigation.tabs.sticky      # Header navigation sticks to the top of the viewport
    - navigation.top              # Adds a "Back to the top" button once you've scrolled down a bit
    - navigation.tracking         # Automatically update the url in the address bar based on the highlighted section of the ToC

plugins:
  - search
  - awesome-pages
  - privacy
  - social:
      cards_layout_options:
        font_family: Dancing Script
        color: "#ffffff"
        background_color: "#4d9bea"

markdown_extensions:
  - toc:
      permalink: true # Adds a link icon to headings
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/joshooaj
      name: joshooaj on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/joshooaj
      name: joshooaj on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/joshooaj
      name: joshooaj on GitHub

nav:
  - Home: README.md
  - Topics:
    - ... | flat | topics/*.md
  - Commands:
    - ... | flat | commands/en-US/*.md
